### ISSUE TITLE
danger-rails_best_practices should not specify rails_best_practices version

### ISSUE THREAD

**Issue by edvakf** [blooper05/danger-rails_best_practices#2]
https://github.com/blooper05/danger-rails_best_practices/blob/master/danger-rails_best_practices.gemspec#L22

It's better give users a freedom to choose any version of `rails_best_practices`.

**Comment by blooper05** [comment]
`danger-rails_best_practices` depends on `RailsBestPractices::Analyzer` class and its methods now. And their API had been changed on some versions. 
So I think it is difficult to support all versions of `rails_best_practices` immediately.

BTW, I'll check that which versions can be supported by current implementation.
